# Generated by Django 5.1.6 on 2025-02-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Groupe',
            new_name='User_Groups',
        ),
    ]
